# Generated by Django 2.2.4 on 2024-08-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmatics_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
