# Generated by Django 2.2.4 on 2024-08-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmatics_app', '0004_auto_20240803_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.FloatField(default='60'),
            preserve_default=False,
        ),
    ]
